version: '3'

services:
  orquideas:
    container_name: orquideas_api 
    restart: unless-stopped
    build: .
    ports:
        - "3000:3000"
    links: 
        - mongodb
    volumes:
      - .:/usr/src/app
  mongodb:
       container_name: orquideasdb
       image: mongo
       ports: 
        - "27018:27017"
  nginx:
   container_name: ngnix_orquideas
   image: nginx
   restart: unless-stopped
   ports:
    - "3001:3000"
   
   volumes:
    - .:/usr/src/app
    


       